"""added aggr_format column

Revision ID: 22ff3d9649ee
Revises: 79f2b4876a6
Create Date: 2013-08-05 12:47:04.508820

"""

# revision identifiers, used by Alembic.
revision = '22ff3d9649ee'
down_revision = '79f2b4876a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('aggr_format', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'aggr_format')
    ### end Alembic commands ###
