"""testing autogenerate revision

Revision ID: 2482fc68028c
Revises: 2e386c75a006
Create Date: 2013-07-25 11:33:01.112005

"""

# revision identifiers, used by Alembic.
revision = '2482fc68028c'
down_revision = '2e386c75a006'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('site_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'site_id')
    ### end Alembic commands ###
