"""testing autogenerate

Revision ID: 3b8142e32b92
Revises: 1dfb0f1edd46
Create Date: 2013-07-26 13:54:49.503351

"""

# revision identifiers, used by Alembic.
revision = '3b8142e32b92'
down_revision = '1dfb0f1edd46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
