"""removed old timestamp column

Revision ID: 481a2e32bf84
Revises: 482d532f4417
Create Date: 2013-07-25 14:08:16.482369

"""

# revision identifiers, used by Alembic.
revision = '481a2e32bf84'
down_revision = '482d532f4417'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captures', u'timestamp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captures', sa.Column(u'timestamp', sa.VARCHAR(), nullable=True))
    ### end Alembic commands ###
