"""added new column for captured_at

Revision ID: 482d532f4417
Revises: 2482fc68028c
Create Date: 2013-07-25 13:32:46.758913

"""

# revision identifiers, used by Alembic.
revision = '482d532f4417'
down_revision = '4d69c0524221'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captures', sa.Column('captured_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captures', 'captured_on')
    ### end Alembic commands ###
