"""changed timestamp to datetime type

Revision ID: 4d69c0524221
Revises: 2482fc68028c
Create Date: 2013-07-25 12:38:01.717191

"""

# revision identifiers, used by Alembic.
revision = '4d69c0524221'
down_revision = '2482fc68028c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('captures', 'timestamp',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('captures', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    ### end Alembic commands ###
