"""added new version of query, modified capture accordingly

Revision ID: 79f2b4876a6
Revises: f564b87e35
Create Date: 2013-07-29 19:05:33.860120

"""

# revision identifiers, used by Alembic.
revision = '79f2b4876a6'
down_revision = 'f564b87e35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('long_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries')
    ### end Alembic commands ###
